apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "UberClient.fullname" . }}
  labels:
    {{ include "UberClient.labels" . | nindent 4 }}
  {{ with .Values.certificate.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  secretName: {{ include "UberClient.fullname" . }}-certificate
  dnsNames:
    - {{ include "UberClient.fullname" . }}
    - {{ include "UberClient.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "UberClient.fullname" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    name: {{ default "ridesaver-ca" .Values.certificate.ca.name }}
    kind: {{ default "ClusterIssuer" .Values.certificate.ca.type }}
