apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "UberClient.fullname" . }}
  labels:
    {{- include "UberClient.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "UberClient.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "UberClient.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "UberClient.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ include "UberClient.fullname" . }}-certificate
          image: alpine/openssl:latest
          command:
            - sh
            - -c
            - "openssl pkcs12 -export -out /pfx/certificate.pfx -inkey /certs/tls.key -in /certs/tls.crt -in /certs/ca.crt -passout pass:"
          volumeMounts:
            - name: certificate
              mountPath: /certs
            - name: pfx-certificate
              mountPath: /pfx
      containers:
        - name: {{ include "UberClient.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pfx-certificate
              mountPath: /certs
              readOnly: true
          env:
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /certs/certificate.pfx
      volumes:
        - name: certificate
          secret:
            secretName: {{ include "UberClient.fullname" . }}-certificate
            optional: false
        - name: pfx-certificate
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
