apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "UberClient.fullname" . }}
  labels:
    {{ include "UberClient.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "UberClient.fullname" . }}-redis
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: lyft-redis
  template:
    metadata:
      labels:
        {{ include "UberClient.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: redis-config
          image: "{{- .Values.redis.image.name -}}:{{ .Values.redis.image.tag }}"
          command:
            - sh
            - '-c'
          args:
            - |
              cp /tmp/redis/redis.conf /etc/redis/redis.conf

              echo "finding master..."
              MASTER_FDQN=`hostname  -f | sed -e 's/redis-[0-9]\./redis-0./'`
              if [ "$(redis-cli -h sentinel -p 5000 ping)" != "PONG" ]; then
                echo "master not found, defaulting to redis-0"

                if [ "$(hostname)" == "redis-0" ]; then
                  echo "this is redis-0, not updating config..."
                else
                  echo "updating redis.conf..."
                  echo "slaveof $MASTER_FDQN 6379" >> /etc/redis/redis.conf
                fi
              else
                echo "sentinel found, finding master"
                MASTER="$(redis-cli -h sentinel -p 5000 sentinel get-master-addr-by-name mymaster | grep -E '(^redis-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
                echo "master found : $MASTER, updating redis.conf"
                echo "slaveof $MASTER 6379" >> /etc/redis/redis.conf
              fi
          volumeMounts:
            - name: node-config
              mountPath: /etc/redis/
            - name: redis-config
              mountPath: /tmp/redis/
      containers:
        - name: redis
          image: {{- .Values.redis.image.name -}}:{{- .Values.redis.image.tag -}}
          command:
            - redis-server
          args:
            - /etc/redis/redis.conf
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: data
              mountPath: /data
            - name: node-config
              mountPath: /etc/redis/
            - name: certs
              mountPath: /certs
          {{ with .Values.redis.resources }}
          resources:
            {{ . | toYaml | nindent 12 }}
          {{ end }}
      volumes:
        - name: node-config
          emptyDir: {}
        - name: certs
          secret:
            secretName: {{ include "UberClient.fullname" . }}-redis-certificate
            optional: false
        - name: redis-config
          configMap:
            name: {{ include "UberClient.fullname" . }}-redis-conf
  volumeClaimTemplates:
    - metadata:
        name: lyft-redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ default "local-storage" .Values.redis.storage.class }}
        {{ with .Values.redis.resources }}
        resources:
          {{ with .requests.storage }}
          requests:
            storage: {{ . }}
          {{ end }}
          {{ with .limits.storage }}
          limits:
            storage: {{ . }}
          {{ end }}
        {{ end }}
