apiVersion: apps/v1
kind: Deployment
metadata:
    name: uber-client
    namespace: client
    labels:
        type: api-client
        client: uber
spec:
    selector:
        matchLabels:
            type: api-client
            client: uber
    replicas: 1
    template:
        metadata:
            labels:
                type: api-client
                client: uber
        spec:
            containers:
                - name: uber
                  image: ghcr.io/ridesaver/uberclient:latest
                  ports:
                      - containerPort: 80
                      - containerPort: 443
            imagePullSecrets:
                - name: github-container-registry
